name: CI

on:
  push:
    branches: [ "ver/1.20.4" ]
  pull_request:
    branches: [ "ver/1.20.4" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          git config --global user.email "663154780@qq.com"
          git config --global user.name "Leleawa"
          ./gradlew applyPatches
          ./gradlew createReobfPaperclipJar
